<a href="https://colab.research.google.com/github/arnicamadera/MO-IT101-Group-13/blob/main/Reyes%2CFK_MS2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
# ============================================
# STEP 1: ANALYZE THE DATASETS
# ============================================

import pandas as pd
import numpy as np

# Load Product List dataset
product_df = pd.read_csv("MotorPH_Products_List_2025.csv")

# Load Sales dataset
sales_df = pd.read_csv("MotorPH_Sales Data-3rd Quarter-Year 2025.csv")

print("Datasets loaded successfully!")

# ============================================
# VIEW FIRST 5 RECORDS
# ============================================

print("===== PRODUCT LIST =====")
display(product_df.head())

print("\n===== SALES DATASET =====")
display(sales_df.head())

# ============================================
# CHECK DATASET STRUCTURE
# ============================================

print("===== PRODUCT LIST STRUCTURE =====")

print("Number of rows:", product_df.shape[0])
print("Number of columns:", product_df.shape[1])

print("\nColumn names:")
print(product_df.columns.tolist())

print("\nData types:")
print(product_df.dtypes)


print("\n\n===== SALES DATASET STRUCTURE =====")

print("Number of rows:", sales_df.shape[0])
print("Number of columns:", sales_df.shape[1])

print("\nColumn names:")
print(sales_df.columns.tolist())

print("\nData types:")
print(sales_df.dtypes)

# ============================================
# DETAILED DATASET INFORMATION
# ============================================

print("===== PRODUCT LIST INFORMATION =====")
product_df.info()

print("\n\n===== SALES DATASET INFORMATION =====")
sales_df.info()

# ============================================
# STATISTICAL SUMMARY
# ============================================

print("===== PRODUCT LIST STATISTICS =====")
display(product_df.describe(include="all"))

print("\n===== SALES DATASET STATISTICS =====")
display(sales_df.describe(include="all"))

# ============================================
# CHECK FOR MISSING VALUES
# ============================================

print("===== PRODUCT LIST MISSING VALUES =====")

product_missing = product_df.isnull().sum()

print(product_missing)
print("\nTotal missing values:",
      product_missing.sum())


print("\n\n===== SALES DATASET MISSING VALUES =====")

sales_missing = sales_df.isnull().sum()

print(sales_missing)
print("\nTotal missing values:",
      sales_missing.sum())

# ============================================
# DISPLAY ROWS WITH MISSING VALUES
# ============================================

print("===== PRODUCT LIST ROWS WITH MISSING VALUES =====")

display(
    product_df[
        product_df.isnull().any(axis=1)
    ]
)


print("\n===== SALES ROWS WITH MISSING VALUES =====")

display(
    sales_df[
        sales_df.isnull().any(axis=1)
    ]
)

# ============================================
# CHECK DUPLICATE RECORDS
# ============================================

print("===== PRODUCT LIST DUPLICATES =====")

print(
    "Number of duplicate rows:",
    product_df.duplicated().sum()
)


print("\n===== SALES DATASET DUPLICATES =====")

print(
    "Number of duplicate rows:",
    sales_df.duplicated().sum()
)

# ============================================
# CHECK DUPLICATE PRODUCT IDs
# ============================================

print("===== PRODUCT ID CHECK =====")

print(
    "Number of unique Product IDs:",
    product_df["EntrNo"].nunique()
)

print(
    "Total Product IDs:",
    len(product_df)
)

print("\nDuplicate Product IDs:")

display(
    product_df[
        product_df["EntrNo"].duplicated(keep=False)
    ]
)

# ============================================
# CHECK DATA TYPES
# ============================================

print("===== PRODUCT LIST DATA TYPES =====")

for column in product_df.columns:
    print(
        f"{column}: {product_df[column].dtype}"
    )


print("\n===== SALES DATA TYPES =====")

for column in sales_df.columns:
    print(
        f"{column}: {sales_df[column].dtype}"
    )

# ============================================
# CHECK DATE FORMATTING
# ============================================

print("===== SALES DATE CHECK =====")

print("Data type:")
print(sales_df["date"].dtype)

print("\nSample dates:")
print(sales_df["date"].head(10))

print("\nNumber of unique dates:")
print(sales_df["date"].nunique())

# ============================================
# CHECK CLIENT TYPE CATEGORIES
# ============================================

print("===== CLIENT TYPE CATEGORIES =====")

print(
    sales_df["client_type"].value_counts(
        dropna=False
    )
)

# ============================================
# CHECK PAYMENT CATEGORIES
# ============================================

print("===== PAYMENT CATEGORIES =====")

print(
    sales_df["payment"].value_counts(
        dropna=False
    )
)

# ============================================
# CHECK SALES PRODUCT NAMES
# ============================================

print("===== SALES PRODUCT NAMES =====")

print(
    "Number of unique product names:",
    sales_df["product"].nunique()
)

print("\nProduct names:")

display(
    pd.DataFrame(
        sorted(
            sales_df["product"]
            .dropna()
            .unique()
        ),
        columns=["Product Name"]
    )
)

# ============================================
# CHECK PRODUCT LIST NAMES
# ============================================

print("===== PRODUCT LIST PRODUCT NAMES =====")

print(
    "Number of unique products:",
    product_df["EntrName"].nunique()
)

display(
    product_df[
        ["EntrNo", "EntrName"]
    ]
)

# ============================================
# CHECK NUMERICAL VALUES
# ============================================

print("===== PRODUCT LIST NUMERICAL COLUMNS =====")

display(
    product_df[
        [
            "Manufacturing Date",
            "Acquisiton",
            "UnitPrice"
        ]
    ].describe()
)


print("\n===== SALES NUMERICAL COLUMNS =====")

display(
    sales_df[
        [
            "Unit Price",
            "quantity",
            "total"
        ]
    ].describe()
)

# ============================================
# CHECK SALES TOTAL CALCULATIONS
# ============================================

sales_df["Calculated Total"] = (
    sales_df["Unit Price"]
    * sales_df["quantity"]
)

incorrect_totals = sales_df[
    sales_df["Calculated Total"]
    != sales_df["total"]
]

print(
    "Number of records with incorrect totals:",
    len(incorrect_totals)
)

display(
    incorrect_totals[
        [
            "date",
            "product",
            "unit price",
            "quantity",
            "total",
            "Calculated Total"
        ]
    ].head(20)
)

# ============================================
# STEP 1 ANALYSIS SUMMARY
# ============================================

print("============================================")
print("       STEP 1: DATASET ANALYSIS SUMMARY")
print("============================================")

print("\nPRODUCT LIST")
print("--------------------------------------------")
print("Rows:", product_df.shape[0])
print("Columns:", product_df.shape[1])
print(
    "Missing values:",
    product_df.isnull().sum().sum()
)
print(
    "Duplicate rows:",
    product_df.duplicated().sum()
)
print(
    "Unique Product IDs:",
    product_df["EntrNo"].nunique()
)
print(
    "Unique Product Names:",
    product_df["EntrName"].nunique()
)


print("\nSALES DATASET")
print("--------------------------------------------")
print("Rows:", sales_df.shape[0])
print("Columns:", sales_df.shape[1])
print(
    "Missing values:",
    sales_df.isnull().sum().sum()
)
print(
    "Duplicate rows:",
    sales_df.duplicated().sum()
)
print(
    "Unique Products:",
    sales_df["product"].nunique()
)
unmatched_products = (
    set(sales_df["product"].dropna())
    - set(product_df["EntrName"].dropna())
)

print(
    "Unmatched Product Names:",
    len(unmatched_products)
)
print(
    "Incorrect Sales Totals:",
    len(incorrect_totals)
)


print("\n============================================")
print("Potential issues identified:")
print("============================================")
print("1. Missing values exist in the Sales dataset.")
print("2. Some columns require data type checking/conversion.")
print("3. Product names contain inconsistent/incorrect entries.")
print("4. Some sales totals do not match Unit Price × Quantity.")
print("5. Duplicate records were checked.")
print("6. Category values were reviewed for consistency.")

# ============================================
# STEP 2: DATA PREPROCESSING
# ============================================

# Create copies so the original datasets are preserved

products = product_df.copy()
sales = sales_df.copy()

print("Copies of the datasets created.")

# ============================================
# RENAME PRODUCT LIST COLUMNS
# ============================================

products = products.rename(columns={
    "EntrNo": "Product ID Number",
    "EntrName": "Product Name",
    "EntrDetails": "Product Details",
    "Manufacturing Date": "Manufacturing Year",
    "Acquisiton": "Acquisiton Year",
    "UnitPrice": "Unit Price"
})

print("Product List columns after renaming:")
print(products.columns.tolist())

# ============================================
# CLEAN PRODUCT LIST TEXT
# ============================================

products["Product Name"] = (
    products["Product Name"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

products["Product Details"] = (
    products["Product Details"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

print("Product text values standardized.")

# ============================================
# CREATE PRODUCT TYPE
# ============================================

products["Product Type"] = (
    products["Product Details"]
    .str.split("/", n=1)
    .str[0]
    .str.strip()
    .str.title()
)

display(
    products[
        [
            "Product Name",
            "Product Type"
        ]
    ].head(10)
)

# ============================================
# CORRECT PRODUCT LIST DATA TYPES
# ============================================

products["Product ID Number"] = pd.to_numeric(
    products["Product ID Number"],
    errors="coerce"
)

products["Manufacturing Year"] = pd.to_numeric(
    products["Manufacturing Year"],
    errors="coerce"
).astype("Int64")

products["Acquisiton Year"] = pd.to_numeric(
    products["Acquisiton Year"],
    errors="coerce"
).astype("Int64")

products["Unit Price"] = pd.to_numeric(
    products["Unit Price"],
    errors="coerce"
)

print("Product List data types after conversion:")
print(products.dtypes)

# ============================================
# REMOVE DUPLICATE PRODUCT RECORDS
# ============================================

before = len(products)

products = products.drop_duplicates()

after = len(products)

print("Records before removing duplicates:", before)
print("Records after removing duplicates:", after)
print("Duplicate records removed:", before - after)

# ============================================
# MAKE PRODUCT IDs SEQUENTIAL
# ============================================

products = products.sort_values(
    "Product ID Number"
).reset_index(drop=True)

products["Product ID Number"] = range(
    1,
    len(products) + 1
)

print("Product IDs have been made sequential.")

display(
    products[
        [
            "Product ID Number",
            "Product Name"
        ]
    ].head(10)
)

# ============================================
# RENAME SALES COLUMNS
# ============================================

sales.columns = [
    "Date",
    "Client Type",
    "Product",
    "Unit Price",
    "Quantity",
    "Total",
    "Payment"
]

print("Sales columns after renaming:")
print(sales.columns.tolist())

# ============================================
# CLEAN SALES TEXT
# ============================================

for column in [
    "Client Type",
    "Product",
    "Payment"
]:

    sales[column] = (
        sales[column]
        .astype("string")
        .str.strip()
        .str.replace(r"\s+", " ", regex=True)
    )

print("Sales text values standardized.")

# ============================================
# CORRECT PRODUCT NAME INCONSISTENCIES
# ============================================

product_name_corrections = {
    "Bajaj CT12x": "Bajaj CT125",
    "Benelli 502x": "Benelli 502C",
    "Bristol Bobber 65x": "Bristol Bobber 650",
    "CFMoto 300Sx": "CFMoto 300SR",
    "Honda ADV 16x": "Honda ADV 160",
    "KTM 790 Dukx": "KTM 790 Duke",
    "Kawasaki KLX 23x": "Kawasaki KLX 230",
    "Motorstar Xplorer 250x": "Motorstar Xplorer 250R",
    "Suzuki Raider R150 Fx": "Suzuki Raider R150 Fi",
    "TVS Apache RTR 200 4x": "TVS Apache RTR 200 4V",
    "Yamaha MT-1x": "Yamaha MT-15",
    "Yamaha Serow 25x": "Yamaha Serow 250",
    "Yamaha Sniper 15x": "Yamaha Sniper 155"
}

sales["Product"] = sales["Product"].replace(
    product_name_corrections
)

print("Product names have been standardized.")

# ============================================
# CORRECT SALES DATA TYPES
# ============================================

sales["Date"] = pd.to_datetime(
    sales["Date"],
    errors="coerce"
)

sales["Unit Price"] = pd.to_numeric(
    sales["Unit Price"],
    errors="coerce"
)

sales["Quantity"] = pd.to_numeric(
    sales["Quantity"],
    errors="coerce"
)

sales["Total"] = pd.to_numeric(
    sales["Total"],
    errors="coerce"
)

print("Sales data types after conversion:")
print(sales.dtypes)

# ============================================
# REMOVE DUPLICATE SALES RECORDS
# ============================================

before = len(sales)

sales = sales.drop_duplicates()

after = len(sales)

print("Records before removing duplicates:", before)
print("Records after removing duplicates:", after)
print("Duplicate records removed:", before - after)

# ============================================
# CHECK MISSING VALUES
# ============================================

print("Missing values in Sales dataset:")
print(sales.isnull().sum)

# ============================================
# HANDLE MISSING VALUES
# ============================================

before = len(sales)

sales = sales.dropna(
    subset=[
        "Date",
        "Client Type",
        "Product",
        "Unit Price",
        "Quantity",
        "Payment"
    ]
)

after = len(sales)

print("Records before removing incomplete transactions:", before)
print("Records after removing incomplete transactions:", after)
print("Incomplete records removed:", before - after)

print("\nMissing values after handling:")
print(sales.isnull().sum())

# ============================================
# STANDARDIZE CATEGORIES
# ============================================

sales["Client Type"] = (
    sales["Client Type"]
    .str.title()
)

sales["Payment"] = (
    sales["Payment"]
    .str.title()
)

print("Client Type categories:")
print(sales["Client Type"].value_counts())

print("\nPayment categories:")
print(sales["Payment"].value_counts())

# ============================================
# MATCH SALES PRODUCTS WITH PRODUCT LIST
# ============================================

price_lookup = dict(
    zip(
        products["Product Name"],
        products["Unit Price"]
    )
)

sales["Unit Price"] = sales["Product"].map(
    price_lookup
)

print("Unmatched products:")

unmatched = sales[
    sales["Unit Price"].isnull()
]

display(
    unmatched[
        ["Product"]
    ].drop_duplicates()
)

# ============================================
# REMOVE UNMATCHED PRODUCTS
# ============================================

before = len(sales)

sales = sales.dropna(
    subset=["Unit Price"]
)

after = len(sales)

print("Unmatched product records removed:", before - after)

# ============================================
# RECALCULATE TOTAL SALES
# ============================================

sales["Unit Price"] = sales["Unit Price"].astype("int64")
sales["Quantity"] = sales["Quantity"].astype("int64")

sales["Total"] = (
    sales["Unit Price"] *
    sales["Quantity"]
).astype("int64")

print("Sales totals recalculated successfully.")

# ============================================
# STANDARDIZE DATE FORMAT
# ============================================

sales["Date"] = sales["Date"].dt.strftime(
    "%Y-%m-%d"
)

print("Date format standardized.")

display(
    sales[["Date"]].head(10)
)

# ============================================
# FINAL PRODUCT LIST STRUCTURE
# ============================================

product_clean = products[
    [
        "Product ID Number",
        "Product Name",
        "Product Type",
        "Manufacturing Year",
        "Acquisiton Year",
        "Unit Price"
    ]
].copy()

print("Clean Product List:")
display(product_clean.head(10))

# ==========================================
# ORGANIZE PRODUCT LIST REPORT
# ==========================================

product = products.rename(columns={
    "Manufacturing Year": "Date of Manufacturing",
    "Acquisiton Year": "Date of Acquisiton"
})

product = product[
    [
        "Product ID Number",
        "Product Name",
        "Product Type",
        "Unit Price",
        "Date of Manufacturing",
        "Date of Acquisiton"
    ]
]

# Make Product ID Number sequential
product["Product ID Number"] = range(1, len(product) + 1)

# Clean text
product["Product Name"] = product["Product Name"].astype(str).str.strip()
product["Product Type"] = product["Product Type"].astype(str).str.strip().str.title()

# Correct numerical formats
product["Product ID Number"] = pd.to_numeric(
    product["Product ID Number"], errors="coerce"
).astype(int)

product["Unit Price"] = pd.to_numeric(
    product["Unit Price"], errors="coerce"
).astype(int)

# Correct year formats
product["Date of Manufacturing"] = pd.to_numeric(
    product["Date of Manufacturing"], errors="coerce"
).astype("Int64")

product["Date of Acquisition"] = pd.to_numeric(
    product["Date of Acquisiton"], errors="coerce"
).astype("Int64")

# Show result
display(product.head(10))

# ==========================================
# VALIDATE PRODUCT LIST REPORT
# ==========================================

print("Columns:")
print(product.columns.tolist())

print("\nMissing values:")
print(product.isnull().sum())

print("\nDuplicate rows:")
print(product.duplicated().sum())

print("\nData types:")
print(product.dtypes)

print("\nDataset shape:")
print(product.shape)

# ============================================
# REVIEW CLEAN PRODUCT LIST
# ============================================

print("===== CLEAN PRODUCT LIST =====")

print("Rows:", product_clean.shape[0])
print("Columns:", product_clean.shape[1])

print("\nMissing values:")
print(product_clean.isnull().sum())

print("\nDuplicate rows:")
print(product_clean.duplicated().sum())

print("\nData types:")
print(product_clean.dtypes)

# ============================================
# REVIEW CLEAN SALES DATASET
# ============================================

print("===== CLEAN SALES DATASET =====")

sales_clean = sales.copy()

print("Rows:", sales_clean.shape[0])
print("Columns:", sales_clean.shape[1])

print("\nMissing values:")
print(sales_clean.isnull().sum())

print("\nDuplicate rows:")
print(sales_clean.duplicated().sum())

print("\nData types:")
print(sales_clean.dtypes)

# ============================================
# VERIFY SALES CALCULATIONS
# ============================================

sales_total_check = (
    sales_clean["Total"]
    ==
    sales_clean["Unit Price"]
    *
    sales_clean["Quantity"]
)

print(
    "Are all Sales Totals correct?",
    sales_total_check.all()
)

# ============================================
# VERIFY PRODUCT MATCHING
# ============================================

product_names = set(
    product_clean["Product Name"]
)

sales_products = set(
    sales_clean["Product"]
)

unmatched_products = (
    sales_products - product_names
)

print("Unmatched products:")
print(unmatched_products)

print(
    "\nAll sales products match Product List:",
    len(unmatched_products) == 0
)

# ============================================
# FINAL PREPROCESSING SUMMARY
# ============================================

print("==========================================")
print("       DATA PREPROCESSING COMPLETE")
print("==========================================")

print("\nPRODUCT LIST")
print("------------------------------------------")
print("Records:", len(product_clean))
print(
    "Missing values:",
    product_clean.isnull().sum().sum()
)
print(
    "Duplicate rows:",
    product_clean.duplicated().sum()
)

print("\nSALES DATASET")
print("------------------------------------------")
print("Records:", len(sales_clean))
print(
    "Missing values:",
    sales_clean.isnull().sum().sum()
)
print(
    "Duplicate rows:",
    sales_clean.duplicated().sum()
)

print(
    "\nSales totals correct:",
    (
        sales_clean["Total"]
        ==
        sales_clean["Unit Price"]
        *
        sales_clean["Quantity"]
    ).all()
)

print(
    "All products matched:",
    set(sales_clean["Product"]).issubset(
        set(product_clean["Product Name"])
    )
)

print("\n==========================================")

# ============================================
# EXPORT CLEANED DATASETS
# ============================================

product_clean.to_csv(
    "preprocessed_product_list.csv",
    index=False
)

sales_clean.to_csv(
    "preprocessed_sales.csv",
    index=False
)

print("Files successfully exported!")
print()
print("preprocessed_product_list.csv")
print("preprocessed_sales.csv")

# ==========================================
# EXPORT PREPROCESSED DATASETS AS NEW CSV
# ==========================================

# Export cleaned Product List
product.to_csv("preprocessed_product_list.csv", index=False)

# Export cleaned Sales data
sales.to_csv("preprocessed_sales.csv", index=False)

print("Both preprocessed datasets were exported successfully!")
print("1. preprocessed_product_list.csv")
print("2. preprocessed_sales.csv")

Datasets loaded successfully!
===== PRODUCT LIST =====

,EntrNo,EntrName,EntrDetails,Manufacturing Date,Acquisiton,UnitPrice
0,1,Honda CBR500R,"Sport / Parallel-twin, liquid-cooled, 471cc, 6...",2021,2023,389000
1,2,Yamaha MT-15,"Naked bike / Single cylinder, liquid-cooled, 1...",2022,2023,178000
2,3,Kawasaki Ninja 400,"Sport / Parallel-twin, liquid-cooled, 399cc, 6...",2023,2024,340000
3,4,Suzuki Raider R150 Fi,"Underbone / Single cylinder, liquid-cooled, 15...",2020,2021,119900
4,5,Royal Enfield Classic 350,"Classic / Single cylinder, air-cooled, 349cc, ...",2022,2023,250000

===== SALES DATASET =====

,date,client_type,product,unitprice,quantity,total,payment
0,7/22/2025,Retail,Zontes GK350,269000,20,5380000,Cash
1,6/15/2025,Wholesale,Yamaha FZi 150,99900,18,1798200,Credit card
2,8/11/2025,Wholesale,Zontes GK350,269000,41,11029000,Credit card
3,7/31/2025,Retail,Italjet Dragster 200,867000,50,14450000,Cash
4,6/21/2025,Wholesale,Zontes 310X,248000,7,1736000,Cash

===== PRODUCT LIST STRUCTURE =====
Number of rows: 50
Number of columns: 6

Column names:
['EntrNo', 'EntrName', 'EntrDetails', 'Manufacturing Date', 'Acquisiton', 'UnitPrice']

Data types:
EntrNo                 int64
EntrName              object
EntrDetails           object
Manufacturing Date     int64
Acquisiton             int64
UnitPrice              int64
dtype: object


===== SALES DATASET STRUCTURE =====
Number of rows: 1000
Number of columns: 7

Column names:
['date', 'client_type', 'product', 'unitprice', 'quantity', 'total', 'payment']

Data types:
date           object
client_type    object
product        object
unitprice       int64
quantity        int64
total           int64
payment        object
dtype: object
===== PRODUCT LIST INFORMATION =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   EntrNo              50 non-null     int64
 1   EntrName            50 non-null     object
 2   EntrDetails         50 non-null     object
 3   Manufacturing Date  50 non-null     int64
 4   Acquisiton          50 non-null     int64
 5   UnitPrice           50 non-null     int64
dtypes: int64(4), object(2)
memory usage: 2.5+ KB


===== SALES DATASET INFORMATION =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         998 non-null    object
 1   client_type  990 non-null    object
 2   product      1000 non-null   object
 3   unitprice    1000 non-null   int64
 4   quantity     1000 non-null   int64
 5   total        1000 non-null   int64
 6   payment      990 non-null    object
dtypes: int64(3), object(4)
memory usage: 54.8+ KB
===== PRODUCT LIST STATISTICS =====

,EntrNo,EntrName,EntrDetails,Manufacturing Date,Acquisiton,UnitPrice
count,50.00000,50,50,50.000000,50.000000,50.000000
unique,NaN,50,47,NaN,NaN,NaN
top,NaN,Honda CBR500R,"Scooter / Single cylinder, liquid-cooled, 155c...",NaN,NaN,NaN
freq,NaN,1,2,NaN,NaN,NaN
mean,25.50000,NaN,NaN,2022.060000,2023.080000,257872.000000
std,14.57738,NaN,NaN,0.998162,0.986439,183425.062316
min,1.00000,NaN,NaN,2020.000000,2021.000000,48000.000000
25%,13.25000,NaN,NaN,2021.250000,2023.000000,126425.000000
50%,25.50000,NaN,NaN,2022.000000,2023.000000,204950.000000
75%,37.75000,NaN,NaN,2023.000000,2024.000000,330250.000000
max,50.00000,NaN,NaN,2023.000000,2024.000000,995000.000000

===== SALES DATASET STATISTICS =====

,date,client_type,product,unitprice,quantity,total,payment
count,998,990,1000,1.000000e+03,1000.000000,1.000000e+03,990
unique,98,2,63,NaN,NaN,NaN,3
top,8/1/2025,Retail,Moto Guzzi V7 Stone,NaN,NaN,NaN,Credit card
freq,21,521,30,NaN,NaN,NaN,354
mean,NaN,NaN,NaN,2.664296e+05,17.749000,4.480788e+06,NaN
std,NaN,NaN,NaN,2.037728e+05,13.307482,4.951406e+06,NaN
min,NaN,NaN,NaN,4.800000e+04,1.000000,6.790000e+04,NaN
25%,NaN,NaN,NaN,1.259000e+05,7.000000,1.294400e+06,NaN
50%,NaN,NaN,NaN,2.100000e+05,15.000000,2.803300e+06,NaN
75%,NaN,NaN,NaN,3.400000e+05,25.000000,6.061500e+06,NaN
max,NaN,NaN,NaN,2.067000e+06,50.000000,3.283500e+07,NaN

===== PRODUCT LIST MISSING VALUES =====
EntrNo                0
EntrName              0
EntrDetails           0
Manufacturing Date    0
Acquisiton            0
UnitPrice             0
dtype: int64

Total missing values: 0


===== SALES DATASET MISSING VALUES =====
date            2
client_type    10
product         0
unitprice       0
quantity        0
total           0
payment        10
dtype: int64

Total missing values: 22
===== PRODUCT LIST ROWS WITH MISSING VALUES =====

Empty DataFrame
Columns: [EntrNo, EntrName, EntrDetails, Manufacturing Date, Acquisiton, UnitPrice]
Index: []

===== SALES ROWS WITH MISSING VALUES =====

,date,client_type,product,unitprice,quantity,total,payment
7,8/14/2025,NaN,KTM 790 Duke,599000,14,8386000,Cash
65,NaN,Retail,Vespa Primavera 150,210000,31,6510000,Credit card
84,6/15/2025,NaN,KTM Duke 200,178000,15,2670000,Cash
119,6/28/2025,Wholesale,Kawasaki Ninja 400,340000,8,2720000,NaN
186,8/9/2025,NaN,Yamaha Sniper 155,125900,8,1007200,Credit card
215,6/1/2025,NaN,Harley-Davidson Street 750,499000,7,3493000,Cash
244,6/19/2025,Wholesale,KTM RC 200,198000,14,2772000,NaN
246,8/6/2025,NaN,Yamaha Aerox 155,124000,18,2232000,Transfer
311,7/3/2025,Wholesale,CFMoto 650MT,345000,3,1035000,NaN
318,7/8/2025,Wholesale,Keeway RKS 150 Sport,68900,15,1033500,NaN
370,NaN,Wholesale,Suzuki Burgman Street 125,80900,47,3802300,Credit card
398,8/25/2025,Wholesale,Yamaha XSR155,182000,19,3458000,NaN
467,8/8/2025,Wholesale,SYM Jet X 150,128000,16,2048000,NaN
492,7/2/2025,Retail,KTM 790 Duke,599000,10,5990000,NaN
524,8/29/2025,NaN,Yamaha Sniper 15x,125900,17,2140300,Credit card
558,7/29/2025,NaN,Yamaha XSR155,182000,12,2184000,Cash
606,6/5/2025,Wholesale,Honda Click 125i,80900,14,1132600,NaN
643,8/16/2025,NaN,Honda ADV 160,494700,9,1484100,Transfer
660,8/19/2025,NaN,Moto Guzzi V7 Stone,689000,14,9646000,Credit card
811,6/17/2025,Retail,Vespa Primavera 150,210000,48,10080000,NaN
896,8/28/2025,NaN,Zontes 310X,248000,8,1984000,Credit card
977,6/14/2025,Wholesale,KTM Duke 200,178000,3,534000,NaN

===== PRODUCT LIST DUPLICATES =====
Number of duplicate rows: 0

===== SALES DATASET DUPLICATES =====
Number of duplicate rows: 0
===== PRODUCT ID CHECK =====
Number of unique Product IDs: 50
Total Product IDs: 50

Duplicate Product IDs:

Empty DataFrame
Columns: [EntrNo, EntrName, EntrDetails, Manufacturing Date, Acquisiton, UnitPrice]
Index: []

===== PRODUCT LIST DATA TYPES =====
EntrNo: int64
EntrName: object
EntrDetails: object
Manufacturing Date: int64
Acquisiton: int64
UnitPrice: int64

===== SALES DATA TYPES =====
date: object
client_type: object
product: object
unitprice: int64
quantity: int64
total: int64
payment: object
===== SALES DATE CHECK =====
Data type:
object

Sample dates:
0    7/22/2025
1    6/15/2025
2    8/11/2025
3    7/31/2025
4    6/21/2025
5    8/22/2025
6    8/26/2025
7    8/14/2025
8    8/14/2025
9    8/27/2025
Name: date, dtype: object

Number of unique dates:
98
===== CLIENT TYPE CATEGORIES =====
client_type
Retail       521
Wholesale    469
NaN           10
Name: count, dtype: int64
===== PAYMENT CATEGORIES =====
payment
Credit card    354
Transfer       328
Cash           308
NaN             10
Name: count, dtype: int64
===== SALES PRODUCT NAMES =====
Number of unique product names: 63

Product names:

         Product Name
0   Aprilia SR GT 200
1        BMW G 310 GS
2         BMW R nineT
3         Bajaj CT125
4         Bajaj CT12x
..                ...
58  Yamaha Sniper 15x
59    Yamaha XMAX 300
60      Yamaha XSR155
61        Zontes 310X
62       Zontes GK350

[63 rows x 1 columns]

===== PRODUCT LIST PRODUCT NAMES =====
Number of unique products: 50

    EntrNo                    EntrName
0        1               Honda CBR500R
1        2                Yamaha MT-15
2        3          Kawasaki Ninja 400
3        4       Suzuki Raider R150 Fi
4        5   Royal Enfield Classic 350
5        6                CFMoto 300NK
6        7          Bristol Veloce 500
7        8                KTM Duke 200
8        9               Yamaha XSR155
9       10           Bajaj Dominar 400
10      11             Yamaha NMAX 155
11      12               Honda ADV 160
12      13           Suzuki Avenis 125
13      14                  KTM RC 200
14      15                BMW G 310 GS
15      16       TVS Apache RTR 200 4V
16      17    Husqvarna Svartpilen 401
17      18         Vespa Primavera 150
18      19             Suzuki GSX-S150
19      20               Kawasaki Z400
20      21            Yamaha Aerox 155
21      22          Bristol Bobber 650
22      23        Keeway RKS 150 Sport
23      24      Motorstar Xplorer 250R
24      25                CFMoto 650MT
25      26            Honda Click 125i
26      27           Yamaha Sniper 155
27      28                 Bajaj CT125
28      29               Honda CRF300L
29      30              Rusi Flash 125
30      31               SYM Jet X 150
31      32  Harley-Davidson Street 750
32      33                 Zontes 310X
33      34           Aprilia SR GT 200
34      35             Yamaha XMAX 300
35      36                Benelli 502C
36      37      Moto Morini X-Cape 650
37      38              Yamaha FZi 150
38      39         Vespa GTS Super 300
39      40            Kawasaki KLX 230
40      41                 BMW R nineT
41      42            Honda Rebel 1100
42      43                KTM 790 Duke
43      44                CFMoto 300SR
44      45        Italjet Dragster 200
45      46            Yamaha Serow 250
46      47   Suzuki Burgman Street 125
47      48                Zontes GK350
48      49         Moto Guzzi V7 Stone
49      50               SYM Husky 150

===== PRODUCT LIST NUMERICAL COLUMNS =====

       Manufacturing Date   Acquisiton      UnitPrice
count           50.000000    50.000000      50.000000
mean          2022.060000  2023.080000  257872.000000
std              0.998162     0.986439  183425.062316
min           2020.000000  2021.000000   48000.000000
25%           2021.250000  2023.000000  126425.000000
50%           2022.000000  2023.000000  204950.000000
75%           2023.000000  2024.000000  330250.000000
max           2023.000000  2024.000000  995000.000000

===== SALES NUMERICAL COLUMNS =====
['date', 'client_type', 'product', 'unitprice', 'quantity', 'total', 'payment']

KeyError: "['UnitPrice'] not in index"

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Load the cleaned MotorPH dataset
product = pd.read_csv("/content/MotorPH_Products_List_2025.csv")

# Count products in each category
category_counts = (
    product["Product Type"]
    .value_counts()
    .sort_values(ascending=True)
)

# Create the horizontal bar chart
fig, ax = plt.subplots(figsize=(10, 7))

bars = ax.barh(
    category_counts.index,
    category_counts.values
)

# Add chart title and axis labels
ax.set_title(
    "MotorPH Product Distribution by Category",
    fontsize=14,
    fontweight="bold",
    pad=15
)
ax.set_xlabel("Number of Products", fontsize=11)
ax.set_ylabel("Product Category", fontsize=11)

# Display the count at the end of each bar
ax.bar_label(bars, padding=4, fontsize=9)

# Improve readability
ax.set_xlim(0, category_counts.max() + 2)
ax.grid(axis="x", linestyle="--", alpha=0.4)
ax.set_axisbelow(True)

# Remove unnecessary borders
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

# Adjust layout and save the chart
plt.tight_layout()
plt.savefig(
    "MotorPH_Product_Distribution.png",
    dpi=300,
    bbox_inches="tight"
)

# Display the chart
plt.show()

In [ ]:
print(product_df.columns.tolist())